### ISSUE TITLE
Comment password encoding limitations

### ISSUE THREAD

**Issue by tomuben** [exasol/r-exasol#114]
## Background
In #113 we fixed only one part, however encoding curly braces correctly is not supported by ODBC driver by now.

## Acceptance Criteria

Encode any occurence of "}" in a password with "}}".

**Comment by redcatbear** [comment]
Asked if internal ticket this depends on can now be solved.

**Comment by redcatbear** [comment]
Please add as "known issue" to the docuementation, since the driver team told us they are not going to fix this.

**Comment by tkilias** [comment]
@redcatbear I put it on the plan for next week.
