### ISSUE TITLE
Add job name to .github/workflows/cpp_test.yml

### ISSUE THREAD

**Issue by kaklakariada** [exasol/r-exasol#115]
github-keeper can only update the branch protection in this repo if a job name is defined in `.github/workflows/cpp_test.yml`:

`Validation Error for .github/workflows/cpp_test.yml: matrix github-action jobs with object parameters and no job name are not supported. Please add a name field to the job that combines the matrix parameters into a more readable name. For example "Build with Go ${{matrix.go}} and Exasol ${{ matrix.db }}"`

**Comment by kaklakariada** [comment]
Sorry, there is another workflow that must be adapted: https://github.com/exasol/r-exasol/blob/main/.github/workflows/windows_macosx.yml

**Comment by tomuben** [comment]
Remaining job-names will be fixed with #120. Closing this one now.
