### ISSUE TITLE
Failed to receive proxy header

### ISSUE THREAD

**Issue by wipatrick** [EXASOL/r-exasol#13]
Calling ```exa.write``` or ```exa.read``` from provided examples causes unknown error.

```{r}
>require(RODBC)
>require(exasol)

>C <- odbcConnect("exasolution")

>odbcQuery(C, "CREATE SCHEMA test")
[1] 1
>odbcQuery(C, "CREATE TABLE test.twogroups (groupid INT, val DOUBLE)")
[1] 1
>exa.writeData(C, twogroups, tableName = "test.twogroups")
Fehler in exa.writeData(C, twogroups, tableName = "test.twogroups") : 
Failed to receive proxy header (0 != 24)
```
```odbcQuery``` gets executed such that schema and table are created in the database.

I'm running on OS X El Capitan (10.11.2) using the following Driver EXASolution_ODBC-5.0.13-MacOS.dmg.

**Comment by marcelboldt** [comment]
I suppose there is a NAT gateway between you and the DB? See #3

**Comment by wipatrick** [comment]
EXASOL VM is running in host-only mode by default settings.

**Comment by marcelboldt** [comment]
I checked the code, it it works. Somehow your EXASOL VM cannot open a connection to your client. You can try https://www.exasol.com/support/browse/SOL-325 for diagnosis...

**Comment by marcelboldt** [comment]
I guess you've been running this on a Mac, too? See issue #3. Its fixed... but ODBC on Mac is still troublesome.
