### ISSUE TITLE
dbConnect() no longer works after update to R 4.2.1 on Windows

### ISSUE THREAD

**Issue by tomazweiss** [exasol/r-exasol#134]
I have two R installations on Windows:
1. R 4.0.4, with exasol package version 5.3.0, and DBI package version 1.1.3.
2. R 4.2.1, with exasol package version 7.1.0, and DBI package version 1.1.3.

When I try to connect to Exasol with the following code, it works without any problems on the first installation, but returns an error on the second one:
```
library(exasol)

con <- dbConnect("exa",
                 dsn = "Exasol",
                 schema = "...",
                 uid = "...",
                 pwd = "...")
```

The error is:
> Error in odbcGetInfo(con) : argument is not an open RODBC channel
In addition: Warning messages:
1: In odbcDriverConnect(con_str) :
  [RODBC] ERROR: state 08004, code -1, message [EXASOL][EXASolution driver]Connection exception - authentication failed.
2: In odbcDriverConnect(con_str) : ODBC connection failed

Let me know if you need more info about my setup.

**Comment by tomuben** [comment]
@tomazweiss , 
1. Please send me the Exasol DB version you are connecting to, and the version of the Exasol ODBC driver installed on your machine.
2 Does the problem also occur with the latest version of `r-exasol` (7.1.0) on R R 4.0.4, or does it happen only on R 4.2.1?

 Thanks.

**Comment by tomazweiss** [comment]
@tomuben 
The Exasol DB version is 7.1.5 and the ODBC driver version was very old - 6.0.0.
I have updated ODBC driver to 7.1.5 and now everything works fine. Thanks!
