### ISSUE TITLE
Is the connection encrypted ?

### ISSUE THREAD

**Issue by vsimko** [exasol/r-exasol#15]
Just a quick question.
Is the connection between the client and server encrypted when using this driver ?

**Comment by marcelboldt** [comment]
It's indeed a good question... Currently not. There is the option to specify ODBC encryption via dbConnect, but that only works for the SQL. Data is currently transferred unencrypted via HTTP. I will review that before a final release (that could be sent to CRAN). However considered that you currently need your client to be reachable from the EXASOL cluster (the cluster opens connections for parallel file transfer), use via plain Internet is for now somehow dodgy anyway.

To be improved together with issue #3.

**Comment by vpulumat** [comment]
Hi ... any update on r-exasol encryption. 

Is the connection between the client and server encrypted when using this driver now ?

**Comment by redcatbear** [comment]
Created feature ticket for TLS support (#56). Will be tracked from there now. Closing this ticket.
