### ISSUE TITLE
Connection fails intermittently with error: No server listening.

### ISSUE THREAD

**Issue by abudis** [exasol/r-exasol#31]
Hi all,

We're seeing a weird error, which happens quite frequently, however I cannot seem to find a pattern for it:

    Error in odbcGetInfo(con) : argument is not an open RODBC channel

In the warnings (I guess coming from the Exasol RODBC library) I see the following:

    Calls: myFunction ... <Anonymous> -> <Anonymous> -> EXANewConnection -> odbcGetInfo
    In addition: Warning messages:
    1: In odbcDriverConnect(con_str) :
    [RODBC] ERROR: state 08S01, code -1, message [unixODBC][EXASOL][EXASolution driver]No server listening.
    2: In odbcDriverConnect(con_str) :
    [RODBC] ERROR: state 08S01, code -1, message [unixODBC][EXASOL][EXASolution driver]No server listening.
    3: In odbcDriverConnect(con_str) : ODBC connection failed

Interestingly, this happens only when I'm trying to write data to the warehouse and only with the r-exasol package, whereas python package seems to be working fine.

Any help appreciated!

**Comment by morazow** [comment]
Hello @abudis,

I am going to close this issue. 
Please try out with latest versions. If issue still occurs, please let us know.
