### ISSUE TITLE
problem with ODBC connection to exasol

### ISSUE THREAD

**Issue by mands2002** [exasol/r-exasol#32]
Hi,
I am trying to run the following code:
```
library(RODBC)
library(exasol)

drv <- dbDriver("exasol") **PASS**
con <- dbConnect(drv, exahost = "host", uid = "my_id", pwd ="my_pass", schema = "SCHEMA") .  **PASS**
dbListTables(con) **Throws an error**
```

error:

Error in try(.Call(C_asyncRODBCQueryFinish, slot, 1)) : 
  Unknown ODBC error
Error in exa.readData(conn, qstr, ...) : 
  Could not allocate SQLAllocHandle
Error in exa.readData(conn, qstr, ...) : Unknown ODBC error

I am using mac, os 10, Exasol ver 5.17, and am able to access the DB from the Exaplus and see tables etc..

thanks!
Shahar

**Comment by Venkat-Rajgopal** [comment]
Is there any update on this ? I have a same issue with Mac OS 10.14. 

error:

```
Error in try(.Call(C_asyncRODBCQueryFinish, slot, 1)) : 
  Unknown ODBC error
Error in exa.readData(conn, statement, ...) : 
  Could not allocate SQLAllocHandle (-2)
Error in exa.readData(conn, statement, ...) : Unknown ODBC error
```

**Comment by exasol-szba** [comment]
Can you tell more about the tools/drivers/components you use? Version numbers and the like?

I have some faint memories of seeing the same (or very similar error message) when I tried to use `unixodbc`. I had to remove it and use `libiodbc`. May it be the source of the issue in your case?

**Comment by sprotou** [comment]
I'm facing the same issue
MacOS 10.14.6
Tried both libiodbc 3.52.13 from brew and unixodbc
Also downloaded and configured based on https://docs.exasol.com/connect_exasol/drivers/odbc/odbc_linux.htm

Exasol 6.2.4

platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock

**Comment by morazow** [comment]
Hey all,

I am going to close this ticket. Please try out with the updated versions.

Please open another ticket if the issue still persists.
