### ISSUE TITLE
Unknown ODBC error. Mac OS. r-exasol

### ISSUE THREAD

**Issue by Venkat-Rajgopal** [exasol/r-exasol#38]
I am trying to connect exasol with R with the following code. The problem occurs with Mac OS. 

```
library(RODBC)
library(exasol)
```

```
con <- dbConnect("exasol", **)
 # removed the connection credentials 

df1 <- dbGetQuery(con,paste("query", sep=""))
 # removed the query

Error in try(.Call(C_asyncRODBCQueryFinish, slot, 1)) : 
  Unknown ODBC error
Error in exa.readData(conn, statement, ...) : 
  Could not allocate SQLAllocHandle (-2)
Error in exa.readData(conn, statement, ...) : Unknown ODBC error`

```
My system is Mac OS "x86_64" .  Please can you help resolving this. ?

**Comment by sprotou** [comment]
I'm also facing the same issue, I believe it is duplicate of https://github.com/exasol/r-exasol/issues/32

Tried both libiodbc and unixodbc

**Comment by morazow** [comment]
Hey all,

I am going to close this ticket. Please try out with the updated versions.

Please open another ticket if the issue still persists.

**Comment by tomuben** [comment]
Root cause seems to be some binary incompatibilty of RODBC package of the MacOsX version on CRAN.
Reinstalling with `install.packages("RODBC", type="source")"` resolves the issue.
