### ISSUE TITLE
connections pane

### ISSUE THREAD

**Issue by KleinhansDa** [exasol/r-exasol#41]
Is there an example on how to add an ExaSol connection to the connections pane?

**Comment by morazow** [comment]
Hello @KleinhansDa,

At the moment, it is not possible to add Exasol to the RStudion connections pane. For that, we have to add [`connections contract`](https://rstudio.github.io/rstudio-extensions/connections-contract.html) to the library.

Mainly a configuration file for Rstudio in `inst/rstudio/` folder.

**Comment by KleinhansDa** [comment]
Too bad!

**Comment by KleinhansDa** [comment]
But thanks for the reply

**Comment by morazow** [comment]
Yes. We may add the configuration in the next releases.

**Comment by KleinhansDa** [comment]
Wonderful
