### ISSUE TITLE
Dummy EXASOL odbc driver needed

### ISSUE THREAD

**Issue by vsimko** [EXASOL/r-exasol#5]
We need a dummy EXASOL odbc driver that would simulate the ODBC communication.
I tried to use SQLITE odbc driver, but SQLITE does not support **EXPORT** SQL command.

**Otherwise, it is hard to write proper unit tests.**

**Comment by marcelboldt** [comment]
A DB instance is now available via ODBC. It is in our public Demo cloud which currently runs on 4 nodes. A connection can be set up on the travis instance with `con <- dbConnect("exa", dsn="exasolution-uo2214lv1_64", schema="PUB864")` the schema parameter is advisable, for PUB864 is a schema with write access to the user (it's empty). 

Thanks again for implementing Travis CI. The more I work with it, the more I like it... :-)
