### ISSUE TITLE
Complete DBI Interface

### ISSUE THREAD

**Issue by tomuben** [exasol/r-exasol#87]
## Background

r-exasol implements the DBI Interface, but not all of the methods are working right now. 
(I checked the first 3 of [this ](https://github.com/r-dbi/DBI/blob/7f29f6b74c56c873a49705f5535f3a7e34b2670c/NAMESPACE) list and they are not working.

## Acceptance Criteria

Implement all remaining methods which are not working.

**Comment by redcatbear** [comment]
Shelved because not in roadmap focus.
