### ISSUE TITLE
Use websockets instead of ODBC

### ISSUE THREAD

**Issue by tomuben** [exasol/r-exasol#88]
## Background

Currently the implementation of r-exasol uses ODBC as the underlying communication protocol with the database. This however has several drawbacks:

- Correct installation and configuration of ODBC driver and DSN
- On MacOsX there is a compatibity issue with the binary RODBC package on CRAN
- ...

Switching to Websockets could resolve some of the issues.

**Comment by redcatbear** [comment]
Shelved because not in roadmap focus.
