### ISSUE TITLE
Problem with exa.writeData in a loop

### ISSUE THREAD

**Issue by vsimko** [EXASOL/r-exasol#9]
Calling `exa.writeData` multiple times in a loop cases socket error.
For example, the following code crashed at iteration 4065.

```r
require(RODBC)
require(exasol)
C <- odbcConnect("exasolution")
for(i in 1:5000) {
  df <- data.frame( ... single row of some data ... )
  exa.writeData(C, df, "mytable")
}
```

```
$ uname -s -r -v -m -p -i -o
Linux 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /proc/meminfo 
MemTotal:       32896676 kB
MemFree:        14085916 kB
Buffers:          133672 kB
Cached:          8216236 kB
SwapCached:         1908 kB
Active:         13122696 kB
Inactive:        5180692 kB
Active(anon):    9936752 kB
Inactive(anon):    16780 kB
Active(file):    3185944 kB
Inactive(file):  5163912 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       2093052 kB
SwapFree:        2075980 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:       9951932 kB
Mapped:            32472 kB
Shmem:                52 kB
Slab:             269212 kB
SReclaimable:     248576 kB
SUnreclaim:        20636 kB
KernelStack:        1160 kB
PageTables:        23472 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    18541388 kB
Committed_AS:   10122864 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       57396 kB
VmallocChunk:   34359669400 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:    33570816 kB
DirectMap2M:           0 kB
```

**Comment by marcelboldt** [comment]
exa.writeData opens a small HTTP based server on the client ánd triggers the DBMS to fetch the data in parallel. Apparently this server cannot handle that many connections... Could be worth thinking about a limit, but the question is whether this had practical use... In comparison to RODBC's sqlQuery method, exa.writeData's overhead causes an additional delay of ~500ms (on my client) PER CONNECTION. That means for very small jobs it is more efficient to use e.g. `sqlQuery(C, paste("insert into test.oltp values (",df[1,1],")"))` (don't forget to disable autocommit for the connection: `C <- dbConnect("exa", dsn="exasolution", autocommit="N")` and commit manually for the commit causes add. delay) - for larger rowsets however exa.writeData performs far better.

That all being said, better do not open so many connections. Send batches of rows in short intervals.
